// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db_queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignInterestsToUser(ctx context.Context, arg AssignInterestsToUserParams) error
	CreateInterest(ctx context.Context, arg CreateInterestParams) (Interest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteInterest(ctx context.Context, id uuid.UUID) error
	GetManyInterestsById(ctx context.Context, ids []uuid.UUID) ([]Interest, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserInterests(ctx context.Context, id uuid.UUID) ([]Interest, error)
	RemoveUser(ctx context.Context, id uuid.UUID) error
	RemoveUserInterest(ctx context.Context, arg RemoveUserInterestParams) error
	UpdateInterestIcon(ctx context.Context, arg UpdateInterestIconParams) (Interest, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
