// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db_queries

import (
	"context"

	"chat_app_backend/internal/extensions"
)

type Querier interface {
	AssignInterestsToUser(ctx context.Context, arg AssignInterestsToUserParams) error
	CreateInterest(ctx context.Context, arg CreateInterestParams) (Interest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteInterest(ctx context.Context, id extensions.UUID) error
	GetInterestById(ctx context.Context, id extensions.UUID) (Interest, error)
	GetManyInterestsByFilters(ctx context.Context, arg GetManyInterestsByFiltersParams) ([]Interest, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id extensions.UUID) (User, error)
	GetUserInterests(ctx context.Context, id extensions.UUID) ([]Interest, error)
	RemoveUser(ctx context.Context, id extensions.UUID) error
	RemoveUserInterest(ctx context.Context, arg RemoveUserInterestParams) error
	UpdateInterestDescription(ctx context.Context, arg UpdateInterestDescriptionParams) (Interest, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
